### ISSUE TITLE
Async/await implementation

### ISSUE THREAD

**Issue by jmagnuson** [jmagnuson/connman-rs#12]
While it probably won't yet replace the existing `futures-0.1` API, it would be useful to gain some more exposure to the new async/await `dbus-rs` code.

**Comment by ivomurrell** [comment]
I've been working on a fork to get `tokio-0.2` integration up and running so I can integrate these bindings with the rest of my crate, though I see you've already started working on a branch yourself!
One thing to note is that there was a bug in the `dbus-tokio` crate which was causing timeouts when large messages were sent over D-Bus (https://github.com/diwic/dbus-rs/issues/254). Connman often sends large payloads so was fairly reliably running into the issue myself. Fortunately, the maintainer (diwic) has fixed the issue now and will hopefully publish a patch in the near future. For now at least you could just pull in the master version of `dbus-rs`?
Just thought I'd chime in as it looks like you're running into the same speed bumps I did! My fork is at https://github.com/MoixaEnergy/connman-rs/tree/tokio-02 for reference.

**Comment by jmagnuson** [comment]
Hey, thanks for the head's-up! Do you think your fork would be upstreamable at some point? Otherwise I can keep combing over mine until it's in a decent state, and likely crib some of your due-diligence (thanks for that, too!).

**Comment by ivomurrell** [comment]
Yes definitely, I noticed your branch only as I was preparing to do a PR! I'll integrate some of the changes you've made and make a PR today then so at the very least you can use my branch as a working example for reference.

**Comment by jmagnuson** [comment]
Closed via #13
